### ISSUE TITLE
DatePicker: Invalid prop value of type string

### ISSUE THREAD

**Issue by luandro** [erikras/redux-form-material-ui#37]
This is how I'm using the DatePicker component:
`<Field name="date" component={DatePicker} hintText="Pick a Date" />`

Getting this error:

```
Failed prop type: Invalid prop `value` of type `string` supplied to `DatePicker`, expected `object`.
    in DatePicker (created by ReduxFormMaterialUIDatePicker)
```

**Comment by aaj** [comment]
Getting this same warning

**Comment by jezstephens** [comment]
It looks like `Field` no longer accepts the `defaultValue` prop, so passing in `defaultValue={null}` has no effect: https://github.com/erikras/redux-form/pull/1593

**Comment by luandro** [comment]
Yea, that doesn't fix it. Should be a simple fix though...

**Comment by rafaelhz** [comment]
the warning is related to the value property, not the defaultValue. The ReduxFormMaterialUIDatePicker is setting an empty string when the initial value of the Redux Form is not defined, the value should be an object.

 I fixed it including a verification in the ReduxFormMaterialUIDatePicker:
**value: inputProps.value !== '' ? inputProps.value : null**

```
export default createComponent(
  DatePicker,
  ({
    input: {
      onBlur, // eslint-disable-line no-unused-vars
      onChange,
      ...inputProps
    },
    ...props
  }) => ({
    ...inputProps,
    ...mapError(props),
    onChange: (event, value) => onChange(value),
    value: inputProps.value !== '' ? inputProps.value : null
  })
)
```

**Comment by pdrummond** [comment]
I am getting this warning too and making the`defaultValue=null` doesn't resolve things for me. I assume the material-ui example is now generating these warnings too?

**Comment by jampy** [comment]
any news on this?

**Comment by felix-d** [comment]
That's because the Material UI `TimePicker` and `DatePicker` components now uses a `Date` object.

redux-form seems to convert any `Date` object passed as an initial value to a string, and the same goes for `null`.

One way around it would be

```javascript

const mapError = ({ meta: { touched, error } = {}, input: { ...inputProps }, ...props }, errorProp = 'errorText') =>
  touched && error ? { ...props, ...inputProps, [errorProp]: error } : { ...inputProps, ...props }

function createComponent(MaterialUIComponent, mapProps) {
  class InputComponent extends Component {
    getRenderedComponent() {
      return this.refs.component;
    }

    render() {
      return createElement(MaterialUIComponent, {
        ...mapProps(this.props),
        ref: 'component',
      });
    }
  }
  InputComponent.displayName = `${MaterialUIComponent.name}`;
  return InputComponent;
}

export default createComponent(TimePicker,
  ({
    input: {
      onBlur,
      onChange,
      value,
      ...inputProps,
    },
    ...props,
  }) => {
    return {
      ...inputProps,
      ...mapError(props),
      value: value && new Date(value) || null,  // THIS IS THE WORKAROUND
      onChange: (event, _value) => onChange(_value),
    };
  }
);
```

Not sure though if this should be added to the codebase, the issue seems deeper than that but I have not dug into redux-form really, maybe there is a reason for that conversion to an empty string. @erikras any input on this?

**Comment by ducminhn** [comment]
@rafaelhz solution works for me. And it makes sense as the Datepicker component need value as an object. Please see my renderDatePicker function:
`const renderDatePicker = ({ input, defaultValue, meta: { touched, error } }) => (
    <DatePicker 
        errorText = {touched && error} 
        {...input}
        value = {input.value !== ''? input.value : null}
        onChange = {(event, value) => {console.log(value); input.onChange(value)}} />
)
`

**Comment by tchri** [comment]
@ducminhn no longer Invalid prop value of type string wth this solution,
but "Uncaught TypeError: Cannot read property 'onBlur' of undefined".

**Comment by Philipp91** [comment]
https://github.com/erikras/redux-form/blob/master/src/createFieldProps.js#L53 This is where the empty string comes from. Here's the change, which also adjusted the documentation: https://github.com/erikras/redux-form/commit/345f46905c4e1bf38b5615b84cb58d507412f323

Providing initialValues is certainly not an option here. In my case, the error occurs before the proper initialValues are available.

To me, filtering out the special value "" and replacing it back with null seems legitimate (i.e. @rafaelhz solution). Though I'm not sure about @erikras reason he put in the Field documentation: Would that make the DatePicker an uncontrolled component? That's certainly not desirable, but what else would you pass to a DatePicker to make it controlled, but empty?

Another possibility could be to use the "format" parameter (https://github.com/erikras/redux-form/blob/master/src/createFieldProps.js#L67), though that would prevent the user from setting their own function there.

**Comment by kyrisu** [comment]
@tchri You are probably still importing DatePicker from _redux-form-material-ui_ where you should be importing it from _material-ui/DatePicker_ for this fix to work.

**Comment by szare** [comment]
@ducminhn, Thank you, it works for me.

**Comment by n0ne** [comment]
@ducminhn, I have this error too:
"Uncaught TypeError: Cannot read property 'onBlur' of undefined".

**Comment by tchri** [comment]
@kyrisu Thank you, it works now!

**Comment by tchri** [comment]
@n0ne, kyrisu gave the answer.

**Comment by restmount** [comment]
@Philipp91 Thanks!

How I fix it:

1. import DatePicker from redux-form-material-ui, not from Material-ui
2. Field component={DatePicker} **format={(value, name) => value === '' ? null : value}**

Good luck!

**Comment by giancarlo88** [comment]
@restmount thanks for that, solved it for me as well.

**Comment by cif** [comment]
I ended up doing this to solve my date issues: `format={value => value ? new Date(value) : null}`  I am using Firebase as a back end so I end up having to convert to and from string anyway. Would be nice to update the component in this lib to check types

**Comment by megkadams** [comment]
Does anyone have a full example of this working ( @cif @kyrisu @Philipp91 ) -- have tried all combinations of above and still can't get it jiving. Would be mucho appreciated!

**Comment by cif** [comment]
@megkadams the DatePicker is expecting a javascript Date object as the prop. To see what you are passing it, do this:

```
<Field 
  name="expiresOn" 
  component={DatePicker} 
  format={(value, name) => { 
    console.log('value being passed:', value);
    console.log('is of type:', typeof value);
    return value === '' ? null : value 
}} />
```
You will then need to use the value being passed to construct a new Date instance, in my example I'm using `new Date(isoStringFmt)` for this purpose

**Comment by erikras** [comment]
You can now pass a `format={null}` to ensure that your `Date` value is not converted to a string.

**Comment by betoharres** [comment]
adding format null did not worked for me, but trying to satisfy PropType by pssing an object did for me.
Just add `value={input.value !== '' ? input.value : {}}` to your DatePicker props.

**Comment by darkfrizer** [comment]
@restmount, @cif  Thanks!

--- restmount comment ---

`import DatePicker from redux-form-material-ui, not from Material-ui
Field component={DatePicker} format={(value, name) => value === '' ? null : value}`

--- cif comment ---
`<Field 
  name="expiresOn" 
  component={DatePicker} 
  format={(value, name) => { 
    console.log('value being passed:', value);
    console.log('is of type:', typeof value);
    return value === '' ? null : value 
}} />
`
so i edit my component like this.

`import {  DatePicker } from 'redux-form-material-ui';

<Field
            name="planDetails.startDate"
            component={DatePicker}
            container="inline"
            autoOk={true}
            format={(value) => value === '' ? null : new Date(value)}
            floatingLabelText="Plan Start" 
            hintText="Plan Start"/>`

**Comment by michabu** [comment]
With values restored from localStorage I did faced the issue that it could whether be a String or a date:
```
<Field
  name="date"
  component={DatePicker}
  format={(value, name) => value === '' ? null : (typeof value === 'string') ? new Date(value) : value}
/>
```

**Comment by lxm7** [comment]
@michabu - I think you saved me from a breakdown at this point, well caught!

**Comment by aronlmin** [comment]
I've tried every pasted example given by everyone and not a single one seems to work =/

**Comment by krs2000** [comment]
Simple and easy solution use moment() instead of new Date() , remember to import moment from "moment";

*************************************************************************
constructor(props) {
		super(props);
		this.state = {
			date:  moment(),
	};
	}

<DatePicker
		selected={this.state.date}
			onChange={date =>
			this.setState({
		date: date
			})
		}
	/>

**Comment by avitorio** [comment]
I know this is an old one but what worked for me was setting propTypes like this:
```
DatePicker.propTypes = {
  date: PropTypes.instanceOf(Date).isRequired,
};
```
